### PR TITLE
Fix issue #156:Create survey questions for Eventing Onboarding Research

### LINKED ISSUE #156: User Research Material: Survey Questions
This sub-issue addresses the creation of survey questions for the Onboarding Experience Study for Knative Eventing (#130). The survey aims to gather quantitative data to identify common challenges, user satisfaction levels, and areas for improvement in the onboarding process.

**Tasks**:
1. Develop a comprehensive set of survey questions targeting new, current, and past users.
2. Ensure the questions cover key areas such as initial setup, documentation clarity, and usability.
3. Review and refine the questions to ensure clarity and effectiveness.

**Link to Main Issue**: [Onboarding Experience Study for Knative Eventing #130](https://github.com/knative/eventing-onboarding-research/issues/130)

### PR DESCRIPTION
**Pull request by firatbezir**
# Changes

- Developed a comprehensive set of survey questions targeting new, current, and past users for the Onboarding Experience Study for Knative Eventing (#156).
- Ensured the questions cover key areas such as initial setup, documentation clarity, and usability.
- Reviewed and refined the questions to ensure clarity and effectiveness.

/kind documentation

Fixes #156

**Release Note**

```release-note
Added survey questions to gather data on user onboarding experiences for Knative Eventing.
```

### CODE REVIEW

**Comment by firatbezir** [comment]
> Hey @firatbezir I think you want: /cc @mmejia02 @Leo6Leo

That's correct @Cali0707, thank you.

**Comment by Leo6Leo** [comment]
/lgtm
/approve

The content of the survey has been reviewed and approved by both @Leo6Leo and @mmejia02 . Here just archive in the GitHub repo for documentation purposes.

**Comment by Cali0707** [comment]
@Leo6Leo @firatbezir can we make this document have the words for the questions in text as well as images? That way, it will be searchable and more accessible

**Comment by Leo6Leo** [comment]
That's right! Thanks for bringing this up! @Cali0707 


Could you add the questions as text to the md file too? @firatbezir

**Pull request merged**
