### PR TITLE
Added Potential Features List to .outcome-template.md

### PR DESCRIPTION
**Pull request by omerbensaadon**
Added Potential Features List

### CODE REVIEW

**Comment by omerbensaadon** [comment]
CC: @csantanapr (I'll avoid self-approving from here on out) :D

**Review by csantanapr — APPROVED** [review]
/approve
/lgtm

**Comment by csantanapr** [comment]
@omerbensaadon 

To assign you can use the "/assign @csantanapr" comment

**Comment by omerbensaadon** [comment]
@csantanapr is there any benefit to doing that vs. manually adding you or are you just validating that I know how to do that? 👍🏼

**Pull request merged**
