### PR TITLE
social media added

### PR DESCRIPTION
**Pull request by Rahul-Kumar-prog**
# Changes

This PR contains social media visuals. specially this PR contain KubeCon + CloudNative visuals with the speaker and talks. also some text for posting this visuals on social media on X ( Twitter ) and LInkedIn. 

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by Leo6Leo** [comment]
@Rahul-Kumar-prog Hello Rahul, can you please provide more context on this PR?

**Comment by Rahul-Kumar-prog** [comment]
> @Rahul-Kumar-prog Hello Rahul, can you please provide more context on this PR?

@Leo6Leo Have a look and let me know. is this context is enough ?

**Comment by Leo6Leo** [comment]
@Rahul-Kumar-prog  Thanks for providing more context in the PR description Rahul.

Did you make these graphics? It looks really great! But the names and profile pictures are not matching. 
For example, currently Dave's picture is at the center, and Luke's picture is at the right. You should switch the names for both of your images.
CleanShot 2024-03-09 at 11 36 17@2x

And if you are intending to use this repo as the storage for those social media post, I think there might be a better place to do so, as GitHub is not designed for that. Storing the posts on Figma should be a better place.

And before you proceeding with posting these posts, I would suggest you to discuss this with @nainaz or @aliok about the marketing strategy if you haven't yet.

WDYT?

/cc @knative/ux-wg-leads

**Comment by Rahul-Kumar-prog** [comment]
@Leo6Leo thankyou for telling me about the mistakes on name and profile.

And I talk to Ali and Naina both. Ali assign me this task and said me to do this. 

Me and Ali both discussed about this.

**Comment by aliok** [comment]
@Leo6Leo, 

@Rahul-Kumar-prog volunteered to handle Knative's social media. We are currently running an experiment to see what works and what doesn't.

He stated he's comfortable with Photoshop and not with Figma/Canva. So, I suggested to send a PR to this repository so that we can review.

Let me know if you have any suggestions.

As I said, we're currently trying to understand what works and what doesn't. UX WG's expertise with design tools are handy here and we would be happy to get your feedback.

@Rahul-Kumar-prog 

I have a few comments:
1. The LinkedIn image needs to `Use a 1.91:1 ratio (1200 x 627 pixels).`
2. Please prepend a date to the files you check in. E.g. `2024-03-11-kubecon....png` (also to MD files) and make the names same for MD and PNG files (e.g. `2023-...-XYZ.md`, `2023-...-XYZ-twitter.png`, `2023-...-XYZ-linkedin.png`) so that we can relate them later on.
3. Please also check in the Photoshop source files. 
4. The text content is a bit light IMO. And we need 2 texts. One for LinkedIn where we don't have a char limit, and one for Twitter where we have a 280 char limit.

**Comment by Cali0707** [comment]
@aliok @Rahul-Kumar-prog I think contributing this to the UX repo makes sense, thanks for the clarification! Let's try this out, and we can discuss more next WG meeting to see if we would like to change anything about this workflow

**Comment by Leo6Leo** [comment]
@aliok  Oh that sounds good, thanks for the clarification. Let's see how everything works together!

And great work to @Rahul-Kumar-prog ! I love the graphics you made.

**Comment by evankanderson** [comment]
I realize we don't have a lot of time, so take this as a pattern for the future, but it would be handy to include alt text (and the original PSD or what-not) when checking in images in the future.  (We can just pull the text from these, but it might be a good future pattern.)

**Comment by Rahul-Kumar-prog** [comment]
> I realize we don't have a lot of time, so take this as a pattern for the future, but it would be handy to include alt text (and the original PSD or what-not) when checking in images in the future. (We can just pull the text from these, but it might be a good future pattern.)

you mean we don't have time kubecon 2024. am I right ?

**Comment by aliok** [comment]
Ok, I made the posts on social media, but I would still like to complete this process to see what parts of the process does work and what doesn't. So, @Rahul-Kumar-prog , can you check in the PSD file?

https://www.linkedin.com/feed/update/urn:li:activity:7173408824073011200

https://twitter.com/KnativeProject/status/1767643811402891489

BTW, I noticed that the text sizes are little bit to small in the visuals:

Screenshot 2024-03-12 at 23 08 59


Screenshot 2024-03-12 at 23 09 12

**Comment by Cali0707** [comment]
> BTW, I noticed that the text sizes are little bit to small in the visuals

Great point @aliok - I think that as we work on the Knative design system we should add guidelines on the text size in graphics. cc @zainabhusain227 @mmejia02

**Comment by Rahul-Kumar-prog** [comment]
Thankyou @aliok @Cali0707 to telling me. I will make changes in designe.

And should I add a source file folder under tha social media to store ai or psd files. That would be better for me and other incoming social media manager to work with those files? 

What POV on it.

And second it I will make a frame size (ratio) in readme to see how its look on LinkedIn and X. For that we can able to imagine how its look on socials?

**Comment by Rahul-Kumar-prog** [comment]
And @aliok something happened with my computer. Sorry if work is delayed

**Comment by Cali0707** [comment]
> And should I add a source file folder under tha social media to store ai or psd files. That would be better for me and other incoming social media manager to work with those files?

@Rahul-Kumar-prog  I think it might make more sense to group things by post. So instead of `socialmedia/images`, we could do `socialmedia/<post name>`, and then add the images, markdown, and PSD files in there. In the future, I think the markdown should also include any text that should be included in the posts, as well as alt text for the images (as @evankanderson recommended)

**Comment by Leo6Leo** [comment]
@Rahul-Kumar-prog It seems like you force-push and reverted all your new changes. 

https://github.com/knative/ux/compare/a40de3ce9aaa83932e120df5404bd79b150ed21b..85f44c9090b32e6eacb0d9f18e5ba61a1018ccaf

**Comment by Rahul-Kumar-prog** [comment]
@Leo6Leo having a problem.
in this pr files I have 5 files instead of the contributions.md file 
but when I see on my repo log it show that all files are added no remaining file.

**Comment by Rahul-Kumar-prog** [comment]
> @Rahul-Kumar-prog It seems like you force-push and reverted all your new changes.
> 
> https://github.com/knative/ux/compare/a40de3ce9aaa83932e120df5404bd79b150ed21b..85f44c9090b32e6eacb0d9f18e5ba61a1018ccaf

yes!
??

**Comment by aliok** [comment]
hey @Rahul-Kumar-prog 

We're working on setting up a process for this work here: https://github.com/knative/community/pull/1445

I really appreciate your efforts here, but we realized that having PSD/PNG files or text content in the repositry makes things complicated.

We now have a Canva account and we have 2 designs that we'll use for LinkedIn and Twitter visuals.

The text doesn't have to be checked in into the repository as well.

I would be very happy if you stick around and start working towards being a social media manager at Knative.

I will reach out to you on Slack now.

**Comment by aliok** [comment]
/close

Let's close this one as our process is much simpler now. I wrote a walk-through on Slack: https://cloud-native.slack.com/archives/C05R3575M9U/p1716378300590869

**Pull request closed without merging**
