### PR TITLE
Contributor Experience Research (Spring 2024)

### PR DESCRIPTION
**Pull request by prajjwalyd**
Here are the key findings and recommendations from the Contributor Experience Research (LFX Term 1). Other relevant details, such as methods used, demographics, limitations, and future work, have also been included. 

I welcome your suggestions, ideas, and potential improvements!

### CODE REVIEW

**Comment by lkingland** [comment]
Thank you for this analysis Prajjwal. 

I find the recommendations to be both common sense and actionable.  Hopefully this contribution is widely read and adopted.  I intend to push for integrating this into Functions, resources permitting.

**Comment by aliok** [comment]
hey @prajjwalyd 

The report looks great. I reviewed half of it at the moment. I want to review the rest too.

I want to ask a few questions though:
- Can you add some demographics information please? I wonder about these:
  - Number of people surveyed
  - Professional experience level
  - Working full/part time on Knative vs not
  - ... other fragmentations that make sense that can still be anonymous
- Methodology to extract findings/recommendations from the survey data
  - I saw this: https://github.com/knative/ux/blob/3ea10c15b41ddd2584919a32086c9e8eb0d33afb/user-research/contributor-research/Introduction.md#methods, but what methods are employed? All of them?
  - Some examples of methodology execution would be very nice. For example, "Based on this and that, we found this group of key findings".
- Is the survey data available somewhere? 
  - If the survey data is large enough that participants can't be identified when the data is anonymized, we can also publish that in our repository.
  - If not, the UX WG leads should have the data stored somewhere private for future uses.
- Can you ask (in private) reviews from the participants?

**Comment by Cali0707** [comment]
Hey @aliok - @prajjwalyd added the demographics!

**Comment by zainabhusain227** [comment]
@prajjwalyd really interesting findings and I liked how there were a variety of recommendations! It could be good to add some details on how you came to those recommendations, whether these were suggested by the interviewees or if there were potential solutions you created based off the challenges identified in the interview. 

I think the recommendations for making more introductory content for knative is great and as a starting point we could point them to existing resources about introductory docker and Kubernetes (videos, articles), sort of like a learning path. We started putting together a Knative information booklet for non-technical contributors that could fit into this larger initiative to create intro content. I think it would also be motivating for contributors to learn about not only the different use cases of Knative but also to learn about what other software is build on top of Knative, e.g. Google' Cloud Run. We could encourage contributors to follow knative's social media where we share use cases etc.

When assigning tasks, its helpful for us to know what peoples prior skillsets are and what they are hoping to learn through contributing to knative. @mmejia02 proposed creating a spreadsheet with new contributors where they can say what they want to work on and then we can assign tasks to people that way. We could have a new spreadsheet every month where active contributors can write what they want to work on. 

I'm also wondering if there is a way we could pair lfx mentees with a brand new contributor once they reach the end of their mentorship. The mentee could help walk the new contributor through a first issue or even create a few new issues based on what was not completed during their mentorship or if they have new ideas they didn't have time to implement. This could help take some of the workload off maintainers as well when it comes to creating new "first issues".

**Comment by prajjwalyd** [comment]
Hey @zainabhusain227, thanks for the review!

> It could be good to add some details on how you came to those recommendations, whether these were suggested by the interviewees or if there were potential solutions you created based off the challenges identified in the interview.

They were a mix of both! The main focus was on the suggestions provided by the interview participants, but there were also some recommendations based on the 'Key Findings,' like the 'monthly hangout calls' and the 'revamped social media presence.' I've included this detail in the first paragraph of the Recommendations.md file. Let me know if further detailing is required!

> I think the recommendations for making more introductory content for Knative are great, and as a starting point, we could point them to existing resources about introductory Docker and Kubernetes (videos, articles), sort of like a learning path.

Yes! That's what I think... We can develop a sort of 'structured onboarding plan' where people, based on their existing knowledge and background, can find resources to learn more about contributing to Knative. For example, if someone already knows about containerization, they can skip that part and move directly to the next topic, and so on...

Also, the rest of the suggestions are really exciting!

**Review by Cali0707 — APPROVED** [review]
/lgtm
/approve

Merging this PR for now... feel free to leave more reviews or open issues and we can do some follow up PRs as needed

**Pull request merged**
